name: flutter_ubuntu_desktop_example
description: Example Flutter desktop app using Canonical's Yaru theme.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  yaru: ^0.0.0-dev.8
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
